### ISSUE TITLE
Actor instantiation failed because: No constructor matches the given number of parameters.

### ISSUE THREAD

**Issue by flaxel** [vlingo/vlingo-actors#82]
**Describe the bug**
We created a project with the [vlingo-xoom-starter](https://github.com/vlingo/vlingo-xoom-starter). Our [project](https://github.com/whzinformatik/stocktrader) is an implementation for the vlingo-stock-trader. We adapt the generated project a little bit and we get an exception that the actor cannot be initialized because the constructors did not match the given number of parameters. The [root cause](https://github.com/vlingo/vlingo-actors/blob/a72753abd7e04bfdf65cad0085737e15776acc99/src/main/java/io/vlingo/actors/ActorFactory.java#L68) is in the ActorFactory line 68-88. 

**To Reproduce**
1. Go to the branch [init_feedback_project](https://github.com/whzinformatik/stocktrader/tree/init_feedback_project) of the stocktrader project
1. Setup the postgres database: `docker-compose up`
1. Execute the program with: `mvn exec:exec`
1. See stacktrace

**Expected behavior**
The project is started and I can send the health request to the feedback project.

**Stacktrace**
This is the Stracktrace if I execute the program:

```
Exception in thread "main" java.lang.NullPointerException
	at io.vlingo.actors.Stage.actorFor(Stage.java:485)
	at io.vlingo.actors.Stage.actorFor(Stage.java:106)
	at io.vlingo.actors.Stage.actorFor(Stage.java:95)
	at io.vlingo.actors.World.actorFor(World.java:126)
	at io.vlingo.xoom.storage.DefaultJournalActorBuilder.build(DefaultJournalActorBuilder.java:22)
	at io.vlingo.xoom.storage.StoreActorBuilder.from(StoreActorBuilder.java:44)
	at com.whz.feedback.infrastructure.persistence.CommandModelJournalProvider.using(CommandModelJournalProvider.java:48)
	at com.whz.feedback.infrastructure.Bootstrap.<init>(Bootstrap.java:47)
	at com.whz.feedback.infrastructure.Bootstrap.main(Bootstrap.java:89)
15:24:23.957 [pool-2-thread-6] ERROR io.vlingo.actors.Logger - Actor instantiation failed because: No constructor matches the given number of parameters.
java.lang.IllegalArgumentException: No constructor matches the given number of parameters.
	at io.vlingo.actors.ActorFactory.actorFor(ActorFactory.java:88) ~[vlingo-actors-1.3.4-20201016.200922-51.jar:na]
	at io.vlingo.actors.Stage.createRawActor(Stage.java:761) ~[vlingo-actors-1.3.4-20201016.200922-51.jar:na]
	at io.vlingo.actors.Stage.actorProtocolFor(Stage.java:526) ~[vlingo-actors-1.3.4-20201016.200922-51.jar:na]
	at io.vlingo.actors.Stage.actorFor(Stage.java:484) ~[vlingo-actors-1.3.4-20201016.200922-51.jar:na]
	at io.vlingo.actors.Stage.actorFor(Stage.java:106) ~[vlingo-actors-1.3.4-20201016.200922-51.jar:na]
	at io.vlingo.actors.Stage.actorFor(Stage.java:95) ~[vlingo-actors-1.3.4-20201016.200922-51.jar:na]
	at io.vlingo.actors.World.actorFor(World.java:126) ~[vlingo-actors-1.3.4-20201016.200922-51.jar:na]
	at io.vlingo.xoom.storage.DefaultJournalActorBuilder.build(DefaultJournalActorBuilder.java:22) ~[vlingo-xoom-1.3.4-20201016.201022-62.jar:na]
	at io.vlingo.xoom.storage.StoreActorBuilder.from(StoreActorBuilder.java:44) ~[vlingo-xoom-1.3.4-20201016.201022-62.jar:na]
	at com.whz.feedback.infrastructure.persistence.CommandModelJournalProvider.using(CommandModelJournalProvider.java:48) ~[classes/:na]
	at com.whz.feedback.infrastructure.Bootstrap.<init>(Bootstrap.java:47) ~[classes/:na]
	at com.whz.feedback.infrastructure.Bootstrap.main(Bootstrap.java:89) ~[classes/:na]
15:24:23.959 [pool-2-thread-6] ERROR io.vlingo.actors.Logger - vlingo/actors: FAILED: Actor instantiation failed because: No constructor matches the given number of parameters.
java.lang.IllegalArgumentException: Actor instantiation failed because: No constructor matches the given number of parameters.
	at io.vlingo.actors.Stage.createRawActor(Stage.java:764) ~[vlingo-actors-1.3.4-20201016.200922-51.jar:na]
	at io.vlingo.actors.Stage.actorProtocolFor(Stage.java:526) ~[vlingo-actors-1.3.4-20201016.200922-51.jar:na]
	at io.vlingo.actors.Stage.actorFor(Stage.java:484) ~[vlingo-actors-1.3.4-20201016.200922-51.jar:na]
	at io.vlingo.actors.Stage.actorFor(Stage.java:106) ~[vlingo-actors-1.3.4-20201016.200922-51.jar:na]
	at io.vlingo.actors.Stage.actorFor(Stage.java:95) ~[vlingo-actors-1.3.4-20201016.200922-51.jar:na]
	at io.vlingo.actors.World.actorFor(World.java:126) ~[vlingo-actors-1.3.4-20201016.200922-51.jar:na]
	at io.vlingo.xoom.storage.DefaultJournalActorBuilder.build(DefaultJournalActorBuilder.java:22) ~[vlingo-xoom-1.3.4-20201016.201022-62.jar:na]
	at io.vlingo.xoom.storage.StoreActorBuilder.from(StoreActorBuilder.java:44) ~[vlingo-xoom-1.3.4-20201016.201022-62.jar:na]
	at com.whz.feedback.infrastructure.persistence.CommandModelJournalProvider.using(CommandModelJournalProvider.java:48) ~[classes/:na]
	at com.whz.feedback.infrastructure.Bootstrap.<init>(Bootstrap.java:47) ~[classes/:na]
	at com.whz.feedback.infrastructure.Bootstrap.main(Bootstrap.java:89) ~[classes/:na]
Caused by: java.lang.IllegalArgumentException: No constructor matches the given number of parameters.
	at io.vlingo.actors.ActorFactory.actorFor(ActorFactory.java:88) ~[vlingo-actors-1.3.4-20201016.200922-51.jar:na]
	at io.vlingo.actors.Stage.createRawActor(Stage.java:761) ~[vlingo-actors-1.3.4-20201016.200922-51.jar:na]
	... 10 common frames omitted
```

And this is the content of the definition if the error occurs: 
<img width="811" alt="Bildschirmfoto 2020-10-20 um 15 50 55" src="https://user-images.githubusercontent.com/19373153/96595763-4f7b6200-12ec-11eb-9dba-56d0db7a9537.png">

**Comment by VaughnVernon** [comment]
@flaxel Thanks. This is apparently a XOOM Starter code generation bug. Would you mind moving it under that repository and assign it to @Florian-Schoenherr.

**Comment by flaxel** [comment]
Thank you for your quick answer. 😄 I created the bug, but I have not the permission to assign this issue to Florian-Schoenherr. Can you add him or can I get the permission?
